#page title
page_title                                : World Heritage (UNESCO Sites)               # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1510826067                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             : https://apps.apple.com/app/id1510826067   # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : /assets/appicon.png                        # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : World Heritage (UNESCO Sites)               # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : FREE                                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Discover the world.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Jules Coynel                                
your_link                                 : http://github.com/jcoynel                     
your_city                                 : Edinburgh 🏴󠁧󠁢󠁳󠁣󠁴󠁿                                
email_address                             : support@coynel.me
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : jcoynel
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : iPhone, iPad and Mac
    description                           : Enjoy the World Heritage app on all your devices.
    fontawesome_icon_name                 : laptop

  - title                                 : Full World Heritage List
    description                           : Browse, search and discover the 1248 UNESCO World Heritage Sites.
    fontawesome_icon_name                 : list

  - title                                 : World Map
    description                           : View all UNESCO World Heritage Sites on a map.
    fontawesome_icon_name                 : map

  - title                                 : Visited List
    description                           : Keep track of the sites you've visited.
    fontawesome_icon_name                 : check-circle

  - title                                 : Favorites List
    description                           : Flag your favorites for a future trip.
    fontawesome_icon_name                 : star

  - title                                 : Import
    description                           : Automatically find visited sites in your photos.
    fontawesome_icon_name                 : magic

  - title                                 : iCloud Sync
    description                           : Your visited sites list and favorites are stored and synced to all your devices with iCloud.
    fontawesome_icon_name                 : cloud

  - title                                 : Statistics
    description                           : Take a glance at your World Heritage sites visits in numbers.
    fontawesome_icon_name                 : chart-pie

  - title                                 : Light or Dark
    description                           : Full support for dark and light themes.
    fontawesome_icon_name                 : adjust
  
  - title                                 : Use Offline
    description                           : View all the sites and your lists offline.
    fontawesome_icon_name                 : wifi


# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#008080"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#008080"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
